.app-build:
  stage: build
  variables:
    META_LAYER_REF: master
    BASE_URL: "https://gitlab.renesas.solutions/api/v4/projects/124/jobs/artifacts"
    SDK_FILENAME: "output/${PLATFORM}/rz-edge-ai-demo-sdk_${PLATFORM}.sh"
    SDK_URL: "${BASE_URL}/${META_LAYER_REF}/raw/${SDK_FILENAME}?access_token=${CI_JOB_TOKEN}&job=sdk_${PLATFORM}"
  before_script:
    - sudo apt update
    - sudo apt upgrade -y bison
  script:
    - printenv
    - echo "Get SDK from ${SDK_URL}"
    - curl --output sdk.sh ${SDK_URL}
    - chmod +x sdk.sh
    - mkdir ${PWD}/toolchain
    - ./sdk.sh -y -d ${PWD}/toolchain
    - source ${PWD}/toolchain/environment-setup-aarch64-poky-linux
    - qmake ${QDEFINES}
    - make
  artifacts:
    name: "${CI_JOB_NAME}-${CI_JOB_ID}"
    when: always
    expire_in: 1 month
    paths:
      - rz-edge-ai-demo

hihope-rzg2m:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-18.04-latest
  extends: .app-build
  variables:
    PLATFORM: hihope-rzg2m

ek874:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-18.04-latest
  extends: .app-build
  variables:
    PLATFORM: ek874

smarc-rzg2l:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  extends: .app-build
  variables:
    PLATFORM: smarc-rzg2l
    QDEFINES: 'DEFINES+=DUNFELL'

smarc-rzg2lc:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  extends: .app-build
  variables:
    PLATFORM: smarc-rzg2lc
    QDEFINES: 'DEFINES+=DUNFELL'
